### PR TITLE
 changed footer to be sticky

### PR DESCRIPTION
**Pull request by hbridges**
Was looking over Ramon's css changes and wanted to make the footer stick to the bottom.

### CODE REVIEW

**Comment by jcrides** [comment]
This might have some conflicts with James' pull request that i just merged. If you can resolve them i'll merge later tonight.

**Comment by hbridges** [comment]
Yeah i can do that but looks like alot of the changes Ramon made were changed in James' latest pull just  style stuff

**Comment by jcrides** [comment]
looks like it's just 2 files that have conflicts, should be pretty easy to fix i think
app/views/layouts/application.html.erb 
app/assets/stylesheets/master.css.scss

**Comment by hbridges** [comment]
Yeah i fixed the conflicts but James' pull kinda changed the Design stuff Ramon had. Like add another header on top of the nav and removed the footer. I changed those back and going to commit it now can look it over and see what you think.

**Comment by jcrides** [comment]
Looks good, we need to figure out where to put the logged in user piece again. merging

**Pull request merged**
