### PR TITLE
Added User Sign In

### PR DESCRIPTION
**Pull request by rachelge13**
Added Devise and a User Sign in link on app/views/layout.html.erb

### CODE REVIEW

**Comment by jcrides** [comment]
Hey Rachel, it looks like this commit is missing the migration file

**Comment by rachelge13** [comment]
Ack. It is. I ran a rake db:migrate with it in there and I had an error
saying it was a duplicate. Any ideas what that's about?

**Comment by jcrides** [comment]
Based on what's in the schema.rb the migration was run but maybe not checked in to git. Try running 
git add db/
and see if it adds the file. Then you should be able to commit and push.

**Comment by rachelge13** [comment]
Will do. Thanks!

**Comment by rachelge13** [comment]
​Still not working. ​Sorry about this, guys! Emailed Ken to see if he has
any idea. I'll add bootstrap in the mean time.

On Fri, Apr 10, 2015 at 9:00 PM, Rachel Geistfeld <
rachel.geistfeld@gmail.com> wrote:

> Will do. Thanks!
> Le 10 avr. 2015 20:59, "Jeremy Carey" <notifications@github.com> a écrit :
>
>> Based on what's in the schema.rb the migration was run but maybe not
>> checked in to git. Try running
>> git add db/
>> and see if it adds the file. Then you should be able to commit and push.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Team-Fischer/chess/pull/1#issuecomment-91739656>.
>>
>


-- 
Rachel Geistfeld
(952).649.0793
rachel.geistfeld@gmail.com
Rachel Likes to Read!
<http://www.youtube.com/user/RachelLikesToRead?feature=watch>

**Comment by jcrides** [comment]
I can manually create the migration file, commit and push. It's a little hacky but I've done similar things at work.

**Comment by rachelge13** [comment]
Okay. Still not getting this to work and it's holding us up. Jeremy, can we do what you suggested?

**Pull request merged**
