### PR TITLE
generated game controller and updated view files

### PR DESCRIPTION
**Pull request by hbridges**
Think this is all i needed to do let me know if i did something wrong or missed something. The link to the show page is current just html, without the  database have no game:id.

### CODE REVIEW

**Comment by kenmazaika** [comment]
Solid, Harvey.

Can you add simpleform in there too?

**Comment by kenmazaika** [comment]
Nice to see TravisCI giving the green light too.  Nice work getting that in there, @helloramon.

**Comment by hbridges** [comment]
yeah ill work on a simpleform

**Comment by hbridges** [comment]
added the simple form gem

**Comment by jcrides** [comment]
Looks good to me, merging

**Pull request merged**
