### PR TITLE
Show users

### PR DESCRIPTION
**Pull request by hbridges**

### CODE REVIEW

**Comment by jjangmes** [comment]
looks goodd

**Comment by jjangmes** [comment]
When I tried the code, I get undefined method for user. because of this line..

**Comment by jjangmes** [comment]
<%= user.where(:id => game.white_user_id).first.email %>

anyone else get the same message?

**Comment by hbridges** [comment]
Im not. Try destroying all your games. might have a game created that wasn't assigned a white user

**Comment by jjangmes** [comment]
worked like a charm. muchas gracias.!

On Thu, May 14, 2015 at 4:55 PM, hbridges <notifications@github.com> wrote:

> Im not. Try destroying all your games. might have a game created that
> wasn't assigned a white user
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Team-Fischer/chess/pull/54#issuecomment-102203730>.
>



-- 
James Lee
(+1) 323-485-3260

**Comment by hbridges** [comment]
NP

**Pull request merged**
