### PR TITLE
Moved obstructed piece to piece model

### PR DESCRIPTION
**Pull request by rachelge13**

### CODE REVIEW

**Comment by jcrides** [comment]
Did you remove the obstructed methods from the queen model?

**Comment by rachelge13** [comment]
Yep!

**Comment by jcrides** [comment]
I don't think that change got committed then. If you look at the pull req it shows only the piece.rb model file being changed. There are no changes in the queen.rb model file.

**Comment by rachelge13** [comment]
It should be good now. Thanks!

**Comment by jcrides** [comment]
Yup it's there now. Looks good, merging.

**Pull request merged**
